In [1]:
#importando bibliotecas 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
!pip install termcolor
from sklearn.model_selection import train_test_split
from termcolor import colored

Requirement already satisfied: termcolor in c:\users\loveb\anaconda3\lib\site-packages (1.1.0)

Lendo dados de treino e teste

In [2]:
# defindo pasta raiz
path = 'Desktop/git/input/test.csv'
train = pd.read_csv(r"C:/Users/loveb/Desktop/git/input/train.csv")
test = pd.read_csv(r"C:/Users/loveb/Desktop/git/input/test.csv")

In [3]:
train.head()

,Id,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
1,3,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
2,4,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
3,6,2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,No
4,8,2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,No

In [4]:
test.head()

,Id,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,1,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,5,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
2,7,2008-12-07,Albury,14.3,25.0,0.0,NaN,NaN,W,50.0,...,49.0,19.0,1009.6,1008.2,1.0,NaN,18.1,24.6,No,No
3,19,2008-12-19,Albury,11.2,22.5,10.6,NaN,NaN,SSE,43.0,...,47.0,32.0,1009.4,1009.7,NaN,2.0,15.5,21.0,Yes,No
4,25,2008-12-25,Albury,12.6,32.4,0.0,NaN,NaN,W,43.0,...,49.0,17.0,1012.9,1010.1,NaN,NaN,21.5,31.2,No,No

In [5]:
# realocando index na base de dados
train.set_index('Date', inplace=True)
test.set_index('Date', inplace=True)
#remover id, nÃ£o nos servirÃ¡ de nada
train.drop(['Id'],axis=1,inplace=True)
test.drop(['Id'],axis=1,inplace=True)

In [6]:
test.head(2)

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,WNW,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,NW,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

In [7]:
train.head()

,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
Date,,,,,,,,,,,,,,,,,,,,,
2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,WSW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,WSW,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,E,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
2008-12-06,Albury,14.6,29.7,0.2,NaN,NaN,WNW,56.0,W,W,...,55.0,23.0,1009.2,1005.4,NaN,NaN,20.6,28.9,No,No
2008-12-08,Albury,7.7,26.7,0.0,NaN,NaN,W,35.0,SSE,W,...,48.0,19.0,1013.4,1010.1,NaN,NaN,16.3,25.5,No,No

In [8]:
#Verificar quantidade de dados faltosos
print(colored('train:\n','red'),train.isnull().sum(),'\n_______-----______\n',colored('test:\n','red'),test.isnull().sum())

train:
 Location             0
MinTemp            498
MaxTemp            251
Rainfall          1146
Evaporation      48500
Sunshine         54087
WindGustDir       7449
WindGustSpeed     7395
WindDir9am        7976
WindDir3pm        3006
WindSpeed9am      1082
WindSpeed3pm      2094
Humidity9am       1402
Humidity3pm       2866
Pressure9am      11155
Pressure3pm      11145
Cloud9am         42798
Cloud3pm         45504
Temp9am            706
Temp3pm           2162
RainToday         1146
RainTomorrow         0
dtype: int64
_______-----______
 test:
 Location             0
MinTemp            139
MaxTemp             71
Rainfall           260
Evaporation      12343
Sunshine         13729
WindGustDir       1881
WindGustSpeed     1875
WindDir9am        2037
WindDir3pm         772
WindSpeed9am       266
WindSpeed3pm       536
Humidity9am        372
Humidity3pm        744
Pressure9am       2859
Pressure3pm       2836
Cloud9am         10859
Cloud3pm         11590
Temp9am            198
Temp3pm            564
RainToday          260
RainTomorrow         0
dtype: int64

In [9]:
#vemos que se removermos os dados para treino apenas usaremos 39% dos dados. Porem pela cÃ©lula 
#anterior vemos que a variÃ¡vel objetivo nÃ£o possue valores faltosos, ou seja, podemos fazer um 
# preenchimento com valores existentes do prÃ³prio dataframe 
train.dropna(axis=0).shape[0]/train.shape[0]*100,test.dropna(axis=0).shape[0]/test.shape[0]*100

(39.824533642773005, 39.094201624529695)

In [10]:
# se assim fizermos nÃ£o zeraremos os valores faltosos. Ainda temos em mente que esse preenchimento nada garante que esses representaram
# os valores reais. No entanto, essa pertubaÃ§Ã£o nos dados tambÃ©m pode contribuir para uma melhor generalizaÃ§Ã£o. assim 
#adotaremos essa tÃ¡tica Juntamente com remoÃ§Ã£o dos valores que ainda permanecerem nan, pois esse sÃ³ preenche com valores anteriores 
# ou posteriores validos e nÃ£o mudaremos o limite de ditanciamento dessa substituiÃ§Ã£o.

train.fillna(method='ffill',inplace=True)
test.fillna(method='ffill',inplace=True)

In [11]:
#quantidade de valores faltosos apÃ³s preenchimento
train.isnull().sum(),test.isnull().sum()

(Location            0
 MinTemp             0
 MaxTemp             0
 Rainfall            0
 Evaporation      4707
 Sunshine         4707
 WindGustDir         0
 WindGustSpeed       0
 WindDir9am          0
 WindDir3pm          0
 WindSpeed9am        0
 WindSpeed3pm        0
 Humidity9am         0
 Humidity3pm         0
 Pressure9am         0
 Pressure3pm         0
 Cloud9am            8
 Cloud3pm            1
 Temp9am             0
 Temp3pm             0
 RainToday           0
 RainTomorrow        0
 dtype: int64,
 Location            0
 MinTemp             0
 MaxTemp             0
 Rainfall            0
 Evaporation      1232
 Sunshine         1232
 WindGustDir         0
 WindGustSpeed       0
 WindDir9am          0
 WindDir3pm          0
 WindSpeed9am        0
 WindSpeed3pm        0
 Humidity9am         0
 Humidity3pm         0
 Pressure9am         0
 Pressure3pm         0
 Cloud9am            0
 Cloud3pm            1
 Temp9am             0
 Temp3pm             0
 RainToday           0
 RainTomorrow        0
 dtype: int64)

In [12]:
#removemdo os valores faltosos
train.dropna(inplace=True)
test.dropna(inplace=True)
# verificar quantidade de valores faltosos
train.isnull().sum().sum(),test.isnull().sum().sum()

(0, 0)

In [13]:
cat_vars = train.select_dtypes(include=['object']).columns.tolist()
cat_vars1 = test.select_dtypes(include=['object']).columns.tolist()

Agora temos que transformar essas variavÃ©is literias em nÃºmericas

In [14]:
#transformando variÃ¡veis Dummys ( Hot encoding)
train= pd.get_dummies(train, columns=cat_vars, drop_first=True)
test= pd.get_dummies(test, columns= cat_vars1, drop_first=True)

In [15]:
train.iloc[500:600,:].head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,...,WindDir3pm_S,WindDir3pm_SE,WindDir3pm_SSE,WindDir3pm_SSW,WindDir3pm_SW,WindDir3pm_W,WindDir3pm_WNW,WindDir3pm_WSW,RainToday_Yes,RainTomorrow_Yes
Date,,,,,,,,,,,,,,,,,,,,,
2010-09-02,14.2,28.3,2.0,4.0,3.9,44.0,13.0,26.0,60.0,21.0,...,0,0,0,0,0,0,0,1,1,1
2010-09-03,13.3,20.8,2.4,6.4,3.9,33.0,17.0,17.0,87.0,71.0,...,0,0,0,0,0,0,0,0,1,1
2010-09-04,14.8,18.0,4.2,0.4,3.9,59.0,28.0,28.0,99.0,71.0,...,0,0,0,0,0,0,0,0,1,1
2010-09-05,7.1,16.3,1.2,2.4,3.9,52.0,13.0,17.0,66.0,49.0,...,0,0,0,0,0,0,0,1,1,0
2010-09-06,5.2,17.8,0.0,2.0,3.9,30.0,7.0,15.0,60.0,39.0,...,0,0,0,0,0,0,0,1,0,0

In [16]:
#separar treino teste 
xtrain, ytrain= train.iloc[:,:-1].to_numpy(), train.iloc[:,-1].to_numpy()
xtest , ytest =test.iloc[:,:-1].to_numpy(), test.iloc[:,-1].to_numpy()
# normalizar dados
# uma vez que temos uma sÃ©rie temporal multvariada, a normalizaÃ§Ã£o mais indicada Ã© a zscore, pois

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
#preserva as caractÃ©risticas originas da sÃ©rie
scaler = StandardScaler()
scaler.fit(xtrain)
xtrain =scaler.transform(xtrain)
scaler.fit(xtest)
xtest = scaler.transform(xtest)

In [21]:

import xgboost as xgb

model = xgb.XGBClassifier()

#treinar modelo
model.fit(xtrain, ytrain)
# gerar predicao
ypred = model.predict(xtest)

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:07:29] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

In [22]:
from sklearn.metrics import (recall_score, accuracy_score, precision_score, f1_score, roc_auc_score)

def show_metrics(model, X_test, y_test,y_pred):
    metrics = {
        'recall': recall_score(y_test,y_pred),
        'accuracy': accuracy_score(y_test,y_pred),
        'precision': precision_score(y_test,y_pred),
        'F1': f1_score(y_test,y_pred),
        'roc_auc': roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
    }
    print(pd.DataFrame.from_dict(metrics, orient='index',columns=['Metrics']))

In [23]:
show_metrics(model, xtest, ytest, ypred)

            Metrics
recall     0.563898
accuracy   0.856030
precision  0.735106
F1         0.638219
roc_auc    0.882096

In [26]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score, cross_validate, cross_val_predict

folds = 10

kfold = StratifiedKFold(n_splits=folds, shuffle = True, random_state=np.random.randint(200))

model = xgb.XGBClassifier(objective="binary:logistic")

In [28]:

# cv_result = cross_val_score(model, X, y, cv=kfold, scoring='roc_auc', verbose=0)
cv_result = cross_validate(model, xtrain, ytrain, cv=kfold, scoring=['recall','accuracy', 'precision', 'f1_macro', 'roc_auc'], verbose=0)
cv_result

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:14:06] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:14:21] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:14:37] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:14:55] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:15:13] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:15:30] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:15:48] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:16:03] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:16:18] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

C:\Users\loveb\anaconda3\lib\site-packages\xgboost\sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)

[22:16:32] WARNING: D:\bld\xgboost-split_1645118015404\work\src\learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

{'fit_time': array([15.46713161, 15.99550319, 17.59107161, 17.76086831, 17.07521367,
        17.60889959, 15.44044995, 14.51986098, 14.53913903, 14.27567267]),
 'score_time': array([0.07268047, 0.07003689, 0.07877779, 0.06290078, 0.06052732,
        0.07457566, 0.06476188, 0.04686952, 0.05634212, 0.05692887]),
 'test_recall': array([0.56293279, 0.56578411, 0.54867617, 0.53971487, 0.5503055 ,
        0.55641548, 0.5694501 , 0.54686227, 0.55641548, 0.53523422]),
 'test_accuracy': array([0.85777166, 0.85767996, 0.85667125, 0.85529574, 0.85703806,
        0.85492893, 0.86272352, 0.85885913, 0.85922597, 0.85427366]),
 'test_precision': array([0.74301075, 0.7408    , 0.74750277, 0.74732092, 0.74806202,
        0.73480366, 0.76060936, 0.75862069, 0.75386313, 0.74574347]),
 'test_f1_macro': array([0.77595115, 0.77639163, 0.77189771, 0.7685115 , 0.77264324,
        0.77143315, 0.78291648, 0.77402468, 0.77637661, 0.76643078]),
 'test_roc_auc': array([0.88823996, 0.89305101, 0.88837337, 0.88446171, 0.88629364,
        0.89102968, 0.89135203, 0.89054629, 0.88901219, 0.88550353])}

In [29]:
def show_cv_metrics(str, cv_result):
    print('{}: {:.4f} +/- {:.4f}'.format(str, cv_result[str].mean(), cv_result[str].std()))

show_cv_metrics('test_recall', cv_result)
show_cv_metrics('test_accuracy', cv_result)
show_cv_metrics('test_precision', cv_result)
show_cv_metrics('test_f1_macro', cv_result)
show_cv_metrics('test_roc_auc', cv_result)

test_recall: 0.5532 +/- 0.0105
test_accuracy: 0.8574 +/- 0.0023
test_precision: 0.7480 +/- 0.0075
test_f1_macro: 0.7737 +/- 0.0044
test_roc_auc: 0.8888 +/- 0.0026